import evaluate
from typing import Union, Sequence, Dict, Any
import pandas as pd

# -------------------------
# Evaluation
# 
# Input:    References (summaries made by human)
#           Predictions (summaries generated by models)
# Output:   Mapping from Scoring Method to actual Score [0-1] 
# ------------------------


class MultiEvaluator:
    """
    Trình đánh giá hỗ trợ tính toán nhiều metric cùng lúc (ROUGE, BERTScore,...)
    và trả về kết quả dạng pandas.DataFrame chi tiết đến từng mẫu.
    """

    def __init__(self, metric_configs: Dict[str, Dict[str, Any]]):
        """
        Khởi tạo các metrics dựa trên cấu hình truyền vào.
        
        Args:
            metric_configs: Dictionary chứa tên metric và các tham số cài đặt sâu của nó.
                            Ví dụ: {'rouge': {'use_stemmer': True}, 'bertscore': {'lang': 'vi'}}
                            Khuyến khích sử dụng từ `ModelConfig`.
        """
        self.metrics = {}
        self.metric_kwargs = metric_configs

        print("[Info] Đang tải các mô hình đánh giá. Việc này có thể mất chút thời gian...")

        for metric_name in metric_configs.keys():
            # evaluate.load() sẽ tải script chuẩn hoặc kéo model từ Hugging Face Hub về
            self.metrics[metric_name] = evaluate.load(metric_name)
            print(f"[Info] Đã tải xong metric: {metric_name}")

    def score_batch(self, 
                    references: Union[Sequence[str], pd.Series], 
                    predictions: Union[Sequence[str], pd.Series]) -> pd.DataFrame:
        """
        Tính điểm hàng loạt và trả về DataFrame.
        """
        # 1. Tiền xử lý đầu vào
        if isinstance(references, pd.Series):
            references = references.tolist()
        if isinstance(predictions, pd.Series):
            predictions = predictions.tolist()
            
        if len(references) != len(predictions):
            raise ValueError("[ERROR] Số lượng bản chuẩn (references) và dự đoán (predictions) phải khớp nhau.")

        # Dictionary tổng để chứa các cột dữ liệu trước khi dựng thành DataFrame
        all_results = {}

        # 2. Quét qua từng metric để tính toán
        for metric_name, metric in self.metrics.items():
            # Lấy các tham số cấu hình riêng của metric đó
            kwargs = self.metric_kwargs.get(metric_name, {})
            
            # TRICK KỸ THUẬT: Ép ROUGE trả về chuỗi điểm thay vì 1 con số trung bình duy nhất
            if metric_name == "rouge":
                kwargs["use_aggregator"] = False
                
            # Chạy tính toán (Hugging Face tự lo tối ưu batch bên dưới)
            match metric_name:
                case _ :
                    raw_scores = metric.compute(predictions=predictions, references=references, **kwargs)
            
            # 3. Trích xuất và định dạng lại tên cột
            for key, values in raw_scores.items():
                # Bỏ qua các dữ liệu rác/metadata (ví dụ BERTScore trả về thêm 'hashcode')
                if key == "hashcode":
                    continue
                    
                # Thêm tiền tố để phân biệt. 
                # Ví dụ: BERTScore trả về key 'f1' -> đổi thành 'bertscore_f1'
                # ROUGE đã có sẵn tên (như 'rouge1', 'rougeLsum') thì giữ nguyên hoặc nối thêm
                if metric_name in key:
                    col_name = key
                else:
                    col_name = f"{metric_name}_{key}"
                
                # Lưu vào dictionary tổng
                all_results[col_name] = values

        # 4. Trả về DataFrame
        return pd.DataFrame(all_results)