import evaluate
from typing import Union, Sequence, Dict, Any, List
import pandas as pd
import json
import re
import requests
from tqdm import tqdm
import traceback

# -------------------------
# Evaluation
# 
# Input:    References (summaries made by human)
#           Predictions (summaries generated by models)
# Output:   Mapping from Scoring Method to actual Score [0-1] 
# ------------------------


class MultiEvaluator:
    """
    Trình đánh giá hỗ trợ tính toán nhiều metric cùng lúc (ROUGE, BERTScore,...)
    và trả về kết quả dạng pandas.DataFrame chi tiết đến từng mẫu.
    """

    def __init__(self, metric_configs: Dict[str, Dict[str, Any]]):
        """
        Khởi tạo các metrics dựa trên cấu hình truyền vào.
        
        Args:
            metric_configs: Dictionary chứa tên metric và các tham số cài đặt sâu của nó.
                            Ví dụ: {'rouge': {'use_stemmer': True}, 'bertscore': {'lang': 'vi'}}
                            Khuyến khích sử dụng từ `ModelConfig`.
        """
        self.metrics = {}
        self.metric_kwargs = metric_configs

        print("[Info] Đang tải các mô hình đánh giá. Việc này có thể mất chút thời gian...")

        for metric_name, config in metric_configs.items():
            # evaluate.load() sẽ tải script chuẩn hoặc kéo model từ Hugging Face Hub về
            match metric_name:
                case name if name.startswith("llm") :
                    self.metrics[metric_name] = LLMEvaluator(config)
                case _ :
                    self.metrics[metric_name] = evaluate.load(metric_name)
            print(f"[Info] Đã tải xong metric: {metric_name}")

    def score_batch(self, 
                    references: Union[Sequence[str], pd.Series], 
                    predictions: Union[Sequence[str], pd.Series],
                    originals: Union[Sequence[str], pd.Series] = None) -> pd.DataFrame:
        """
        Tính điểm hàng loạt và trả về DataFrame.
        """
        # 1. Tiền xử lý đầu vào
        if isinstance(references, pd.Series):
            references = references.tolist()
        if isinstance(predictions, pd.Series):
            predictions = predictions.tolist()
            
        if len(references) != len(predictions):
            raise ValueError("[ERROR] Số lượng bản chuẩn (references) và dự đoán (predictions) phải khớp nhau.")

        # Dictionary tổng để chứa các cột dữ liệu trước khi dựng thành DataFrame
        all_results = {}

        # 2. Quét qua từng metric để tính toán
        for metric_name, metric in self.metrics.items():
            # Lấy các tham số cấu hình riêng của metric đó
            kwargs = self.metric_kwargs.get(metric_name, {})
            
            # TRICK KỸ THUẬT: Ép ROUGE trả về chuỗi điểm thay vì 1 con số trung bình duy nhất
            if metric_name == "rouge":
                kwargs["use_aggregator"] = False
                
            # Chạy tính toán (Hugging Face tự lo tối ưu batch bên dưới)
            match metric_name:
                case name if name.startswith("llm") :
                    raw_scores = metric.compute(originals, references, predictions)
                case _ :
                    raw_scores = metric.compute(predictions=predictions, references=references, **kwargs)
            
            # 3. Trích xuất và định dạng lại tên cột
            for key, values in raw_scores.items():
                # Bỏ qua các dữ liệu rác/metadata (ví dụ BERTScore trả về thêm 'hashcode')
                if key == "hashcode":
                    continue
                    
                # Thêm tiền tố để phân biệt. 
                # Ví dụ: BERTScore trả về key 'f1' -> đổi thành 'bertscore_f1'
                # ROUGE đã có sẵn tên (như 'rouge1', 'rougeLsum') thì giữ nguyên hoặc nối thêm
                if metric_name in key:
                    col_name = key
                else:
                    col_name = f"{metric_name}_{key}"
                
                # Lưu vào dictionary tổng
                all_results[col_name] = values

        # 4. Trả về DataFrame
        return pd.DataFrame(all_results)
    
        
class LLMEvaluator:
    """
    LLM-as-a-Judge evaluator.

    Supported providers:
    - local (Transformers)
    - groq
    - ollama
    """

    def __init__(self, config):
        self.provider = config.get("provider", "local").lower()
        self.model_name = config.get("model_name")

        self.prompt = config.get("prompt")
        self.response_key = config.get("response_key")

        assert self.prompt is not None
        assert self.response_key is not None

        print(
            f"[Info] Khởi tạo LLMEvaluator | "
            f"provider={self.provider} | "
            f"model={self.model_name}"
        )

        # -----------------------------
        # LOCAL
        # -----------------------------
        if self.provider == "local":
            import torch
            from transformers import (
                AutoTokenizer,
                AutoModelForCausalLM,
            )

            self.torch = torch

            self.tokenizer = AutoTokenizer.from_pretrained(
                self.model_name,
                trust_remote_code=True
            )

            self.model = AutoModelForCausalLM.from_pretrained(
                self.model_name,
                dtype=torch.float16,
                device_map="auto",
                trust_remote_code=True
            )

            self.model.eval()

            print(
                "[Info] Model loaded on:",
                self.model.device
            )

        # -----------------------------
        # GROQ
        # -----------------------------
        elif self.provider == "groq":
            from groq import Groq

            self.api_key = config.get("api_key")

            if not self.api_key:
                raise ValueError(
                    "[ERROR] Thiếu api_key cho Groq"
                )

            self.client = Groq(api_key=self.api_key)

        # -----------------------------
        # OLLAMA
        # -----------------------------
        elif self.provider == "ollama":
            self.url = config.get(
                "url",
                "http://localhost:11434/api/generate"
            )

        else:
            raise ValueError(
                f"Unsupported provider: {self.provider}"
            )

    # ==================================================
    # PROMPT
    # ==================================================

    def _build_prompt(
        self,
        original,
        reference,
        prediction
    ):
        return self.prompt.format(
            original=original,
            reference=reference,
            prediction=prediction
        )

    # ==================================================
    # PARSE JSON
    # ==================================================

    def _parse_llm_response(self, text):
        import json
        import re

        try:
            candidates = re.findall(
                r"\{.*?\}",
                text,
                flags=re.DOTALL
            )

            if not candidates:
                raise ValueError(
                    "No JSON object found"
                )

            parsed = json.loads(candidates[-1])

            return {
                key: parsed.get(key, 0)
                for key in self.response_key
            }

        except Exception:
            print(
                f"[Warning] Cannot parse JSON:\n{text}"
            )

            return {
                key: 0.0
                for key in self.response_key
            }

    # ==================================================
    # LOCAL GENERATION
    # ==================================================

    def _generate_local(self, prompt):

        messages = [
            {
                "role": "user",
                "content": prompt
            }
        ]

        text = self.tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )

        inputs = self.tokenizer(
            text,
            return_tensors="pt"
        )

        inputs = {
            k: v.to(self.model.device)
            for k, v in inputs.items()
        }

        with self.torch.no_grad():

            outputs = self.model.generate(
                **inputs,
                max_new_tokens=256,
                do_sample=False,
                pad_token_id=self.tokenizer.eos_token_id,
                eos_token_id=self.tokenizer.eos_token_id
            )

        generated_ids = outputs[0][
            inputs["input_ids"].shape[1]:
        ]

        response = self.tokenizer.decode(
            generated_ids,
            skip_special_tokens=True
        )

        return response

    # ==================================================
    # MAIN COMPUTE
    # ==================================================

    def compute(
        self,
        originals,
        references,
        predictions
    ):

        from tqdm import tqdm
        import traceback
        import requests

        results = {
            key: []
            for key in self.response_key
        }

        if originals is None:
            originals = [
                "(Không cung cấp)"
            ] * len(references)

        progress_bar = tqdm(
            zip(
                originals,
                references,
                predictions
            ),
            total=len(predictions),
            desc="LLM judge progress"
        )

        for orig, ref, pred in progress_bar:

            prompt = self._build_prompt(
                orig,
                ref,
                pred
            )

            try:

                # -----------------
                # LOCAL
                # -----------------

                if self.provider == "local":

                    response_text = (
                        self._generate_local(
                            prompt
                        )
                    )

                # -----------------
                # GROQ
                # -----------------

                elif self.provider == "groq":

                    completion = (
                        self.client.chat.completions.create(
                            model=self.model_name,
                            messages=[
                                {
                                    "role": "user",
                                    "content": prompt
                                }
                            ],
                            response_format={
                                "type": "json_object"
                            }
                        )
                    )

                    response_text = (
                        completion
                        .choices[0]
                        .message.content
                    )

                # -----------------
                # OLLAMA
                # -----------------

                elif self.provider == "ollama":

                    payload = {
                        "model": self.model_name,
                        "prompt": prompt,
                        "stream": False,
                        "format": "json"
                    }

                    response = requests.post(
                        self.url,
                        json=payload
                    )

                    response.raise_for_status()

                    response_text = (
                        response.json()
                        .get("response", "")
                    )

                scores = self._parse_llm_response(
                    response_text
                )

                for key in self.response_key:
                    results[key].append(
                        scores.get(key, 0.0)
                    )

            except Exception as e:

                print(
                    f"[Lỗi] Fail khi đánh giá mẫu: {e}"
                )

                traceback.print_exc()

                for key in self.response_key:
                    results[key].append(0.0)

        return results